apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./repository/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
    namespace: flux-system
  targetNamespace: monitoring
