apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "8.6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: app-monitor.local
          paths:
            - path: /
              pathType: Prefix
    persistence:
      enabled: true
      size: 5Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
            isDefault: true
