apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 53.2.0   # example — pin to specific chart version you prefer
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  values:
    grafana:
      service:
        type: LoadBalancer   # if you have MetalLB; otherwise use NodePort
      sidecar:
        dashboards:
          enabled: true
        datasources:
          enabled: true
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
