apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      version: "2.10.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m  # ← REQUIRED FIELD - Add this!
  install:
    createNamespace: true
    timeout: 10m
  values:
    loki:
      enabled: true
      config:
        auth_enabled: false
      persistence:
        enabled: true
        size: 5Gi
        storageClassName: local-path
    promtail:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false