apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: "6.6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    # Use simple mode instead of microservices
    singleBinary:
      enabled: true
      replicas: 1
    
    # Disable enterprise features
    enterprise:
      enabled: false
    
    # Simple configuration
    loki:
      config:
        auth_enabled: false
        common:
          storage:
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
        ingester:
          lifecycler:
            address: 127.0.0.1
            ring:
              kvstore:
                store: inmemory
            replication_factor: 1
          chunk_idle_period: 3m
          chunk_target_size: 1536000
          max_chunk_age: 1h
        limits_config:
          reject_old_samples: true
          reject_old_samples_max_age: 168h
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
        server:
          http_listen_port: 3100
          grpc_listen_port: 9095
        storage_config:
          boltdb_shipper:
            active_index_directory: /var/loki/boltdb-shipper-active
            cache_location: /var/loki/boltdb-shipper-cache
            shared_store: filesystem
    
    # Service configuration
    service:
      enabled: true
      type: ClusterIP
      port: 3100
      targetPort: 3100
    
    # Persistence
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
    
    # Disable unnecessary components
    write:
      enabled: false
    read:
      enabled: false
    backend:
      enabled: false
    gateway:
      enabled: false
    test:
      enabled: false
    memcached:
      enabled: false
    memcachedChunks:
      enabled: false