apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: "6.6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    # Enable the Loki service
    service:
      enabled: true
      type: ClusterIP
      port: 3100
      targetPort: 3100
      annotations: {}
    
    # Basic configuration
    config:
      auth_enabled: false
      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 1h
        max_chunk_age: 1h
        chunk_target_size: 1048576
        chunk_retain_period: 30s
        max_transfer_retries: 0
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        allow_structured_metadata: false
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      server:
        http_listen_port: 3100
        grpc_listen_port: 9096
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          shared_store: filesystem
        filesystem:
          directory: /data/loki/chunks
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
    
    # Persistence configuration
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path  # Use k3s default storage class
      annotations: {}
    
    # Single mode for development
    singleBinary:
      enabled: true
      replicas: 1
    
    # Disable unnecessary components
    read:
      enabled: false
    write:
      enabled: false
    backend:
      enabled: false
    gateway:
      enabled: false
    test:
      enabled: false