apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-distributed
      version: "1.6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    timeout: 10m
  values:
    # Use single binary mode for simplicity
    singleBinary:
      enabled: true
      replicas: 1

    # Simple configuration
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      common:
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/boltdb-shipper-active
          cache_location: /var/loki/boltdb-shipper-cache
          shared_store: filesystem

    # Service
    service:
      enabled: true
      port: 3100

    # Persistence
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce

    # Disable all enterprise and complex features
    enterprise:
      enabled: false

    # Disable unnecessary components
    gateway:
      enabled: false
    test:
      enabled: false
    memcached:
      enabled: false
    memcachedChunks:
      enabled: false

    # Resources
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m