apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.6.4
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 10Gi
