apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 6.6.6
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  values:
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    schemaConfig:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    storage:
      type: filesystem
      filesystem:
        chunksDirectory: /data/loki/chunks
        rulesDirectory: /data/loki/rules
