apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: "6.6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    # Minimal working configuration
    mode: single
    singleBinary:
      enabled: true
    
    # Disable all enterprise and complex features
    enterprise:
      enabled: false
    
    # Simple config
    config:
      auth_enabled: false
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
      server:
        http_listen_port: 3100
      storage_config:
        filesystem:
          directory: /var/loki/chunks
    
    # Service
    service:
      enabled: true
      port: 3100
    
    # Persistence
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-path