apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: "5.*"  # Use an older, more stable version
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    timeout: 10m
  values:
    # Use single binary mode - this is CRITICAL
    singleBinary:
      enabled: true
      replicas: 1
    
    # Disable ALL enterprise features
    enterprise:
      enabled: false
    
    # Minimal config - avoid complex configurations
    config: |
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095
      common:
        ring:
          kvstore:
            store: inmemory
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/boltdb-shipper-active
          cache_location: /var/loki/boltdb-shipper-cache
          shared_store: filesystem
    
    # Service
    service:
      enabled: true
      port: 3100
    
    # Persistence
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-path
    
    # Disable ALL additional components
    write:
      enabled: false
    read:
      enabled: false
    backend:
      enabled: false
    gateway:
      enabled: false
    test:
      enabled: false