apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.5
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
