apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.15.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: wordpress|ingress-nginx
