apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.15.*"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  install:
    createNamespace: true
  values:
    config:
      server:
        http_listen_port: 3101
        grpc_listen_port: 0
      positions:
        filename: /run/promtail/positions.yaml
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              # Keep only WordPress and ingress-nginx pods
              - source_labels: [__meta_kubernetes_pod_label_app]
                regex: wordpress|ingress-nginx
                action: keep
              # Add namespace, pod, and container labels
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              # Map all pod labels
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
