apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 15m
  path: "./repository/wordpress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: wordpress