apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  path: "./repository/metalLB"
  prune: true
  sourceRef:
    kind: GitRepository
    name: metalLB