apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mysql
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/delwarhossainhimel/fluxcd-with-k3s