apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mysql
  namespace: default
spec:
  interval: 15m
  path: "./repository/mysql"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mysql