apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: ingress-nginx
spec:
  selector:
    app: dummy
  ports:
    - port: 80
      targetPort: 80
