apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 15m
  path: ./repository/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-nginx