apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-lua-404
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    -- simple redirect: immediately redirect to google
    return ngx.redirect("https://www.google.com", 302)
