apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress-mysql
  name: wordpress-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
      #   volumeMounts:
      #   - name: mysql-data
      #     mountPath: /var/lib/mysql
      #     subPath: db-mysql
      #   resources:
      #     requests:
      #       memory: "300Mi"
      #       cpu: "250m"
      #     limits:
      #       memory: "500Mi"
      #       cpu: "500m"  
      # volumes:
      # - name: mysql-data
      #   persistentVolumeClaim:
      #     claimName: nfs-wordpress-mysql-volume

status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-mysql
    