apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx
  namespace: flux-system 
spec:
  interval: 1m
  url: https://github.com/delwarhossainhimel/fluxcd-with-k3s
  ref:
    branch: main
